---
title: "Vinhos"
author: "Matheus, Murilo"
output:
  pdf_document: default
  html_document: default
---
##pacotes
```{r pacotes}
source("func.R")
# packages
packages <- c("Rcpp",
              "tidyverse",
              "magrittr",
              "tidyverse",
              "broom",
              "corrplot",
              "ca",
              "RColorBrewer",
              "gridExtra",
              "forcats",
              "rpart",
              "rpart.plot",
              "pROC",
              "randomForest",
              "caret",
              "xtable")

ipak(packages)

#library(devtools)
#install_github("vqv/ggbiplot")
```

##Carregando os dados

```{r}
##leitura dos dados
red <- read.csv("winequality/winequality-red.csv",header = T,sep = ";") %>% 
  mutate(vinho = as.factor("red"))

white <- read.csv("winequality/winequality-white.csv",header = T,sep = ";") %>% mutate(vinho =as.factor("white"))
dados <- rbind(white,red)

```
##Descritivas

```{r results = "asis" }
dados %<>% mutate( quality = as.numeric(quality),
                  qualidade = lvls_reorder(map_chr(quality,cl),c(2,3,1)))

corrplot::corrplot(cor(dados[1:12]),method="ellipse",order = "hclust", addrect=NULL)

cbind(
cor(x=red[,1:11], y=red$quality),
cor(x=white[,1:11], y=white$quality))
indep <- c("vinho","volatile.acidity","sulphates","alcohol",
           "density","chlorides")
data <- dados %>% select(indep,quality,qualidade)
corrplot::corrplot(cor(data[2:5]),method="ellipse",order = "hclust", addrect=NULL)
set.seed(1)
sample_rows <- sample(1:nrow(data), nrow(data)*.75)
train <- data[sample_rows,]
test <- data[-sample_rows,]
glimpse(dados)
dados %<>% mutate( quality = as.numeric(quality),
                  qualidade = lvls_reorder(map_chr(quality,cl),c(2,3,1)))
options(xtable.comment = FALSE)
descritivas <- 
dados %>% select_if(.predicate = is.numeric) %>% 
  gather(coluna,valores) %>% 
  group_by(Coluna = coluna) %>% 
  summarise_if(.predicate = function(x) is.numeric(x),
                  .funs = c(Media = "mean",
                     DP = "sd",
                     Var. = "var",
                     Minimo = "min",
                     CV =  "cv",
                     Mediana = "median",
                     Maximo = "max")) %>% 
  mutate_if(.predicate = is.numeric,funs(round(.,3)))
xtable(descritivas,caption = "Medidas Descritivas",digits = 3)



```

##variavel resposta

```{r}
ggplot(dados,aes(quality),fill = "blue") + stat_count(fill = "blue",aes(y = (..count..)/sum(..count..))) +
  theme_bw() +
  labs(x = "Qualidade",y="Proporção")
table(dados$quality)
prop.table(table(dados$quality))

ggplot(dados,aes(qualidade),fill = "blue") + stat_count(fill = "blue",aes(y = (..count..)/sum(..count..))) +
  theme_bw() +
  labs(x = "Qualidade",y = "Proporção")

```

```{r}
#ANALISANDO POSSIVEIS VARIAVEIS INFLUENTES NA ANALISE NA QUALIDADE DO VINHO
#Começarei analisando o alcool, açucar, ph
myCol <- brewer.pal(8, "Dark2")
dados %<>%  mutate(quality = factor(quality))
p1 <- dados %>% ggplot(aes(quality,alcohol,fill = quality,group = quality)) +
  geom_boxplot(show.legend = F) +
  theme_bw() +
  labs(y="Porcentagem (%)", title = "Porcentagem de Alcool por\n Qualidade",x=NULL) +
  theme(plot.title = element_text(size = 12,lineheight=.8,  
  face="bold",hjust = 0.5),text=element_text(size=12,  family="sans")) +
  scale_fill_manual(values = myCol) 


p2 <- dados %>% ggplot(aes(quality,pH,fill = quality,group = quality)) +
  geom_boxplot(show.legend = F) +
  theme_bw() +
  labs(y="Valores do pH (0-14)", title = "pH do vinho por\n Qualidade",x=NULL) +
  theme(plot.title = element_text(size = 12,lineheight=.8,  
  face="bold",hjust = 0.5),text=element_text(size=12,  family="sans")) +
  scale_fill_manual(values = myCol) 


p3 <- dados %>% ggplot(aes(quality,residual.sugar,fill = quality,group = quality)) +
  geom_boxplot(show.legend = F) +
  theme_bw() +
  labs(y="Açucar residual (gramas)", title = "Açucar residual por\n Qualidade",x=NULL) +
  theme(plot.title = element_text(size = 12,lineheight=.8,  
  face="bold",hjust = 0.5),text=element_text(size=12,  family="sans")) +
  scale_fill_manual(values = myCol) 


p4 <- dados %>% ggplot(aes(quality,density,fill = quality,group = quality)) +
  geom_boxplot(show.legend = F) +
  theme_bw() +
  labs(y="Valores da densidade do vinho", title = "Densidade do vinho por\n Qualidade",x=NULL) +
  theme(plot.title = element_text(size = 12,lineheight=.8,  
  face="bold",hjust = 0.5),text=element_text(size=12,  family="sans")) +
  scale_fill_manual(values = myCol) 

grid.arrange(p1,p2,p3,p4)
```

##Florestas

```{r arvore de decisao}
dados %<>% mutate(quality = as.numeric(quality))

##floresta Regressao
rf_model <- randomForest(quality ~. - qualidade,data = dados,  importance=TRUE ,ntree = 100)


predito <- round(predict(rf_model))
table(predicao=predito, observado=dados$quality)
mean(predito == dados$quality)
varImpPlot(rf_model,main = "Importância das Variáveis",type = 2)

##floresta 2.0 Classificação

rf_model <- randomForest(qualidade ~. - quality,data = dados,  importance = TRUE ,ntree = 100)


predito <- predict(rf_model)
confusionMatrix(predito,dados$qualidade)
table(Predito = predito,Referência = dados$qualidade)
varImpPlot(rf_model,main = "Importância das Variáveis",type = 2)
impToPlot <- importance(rf_model, scale=FALSE)
dotchart(sort(impToPlot[,5]), xlim=c(0,600), xlab="Gini",main ="Importância das Variáveis" )
##Arvore Classificação
set.seed(1)
tree <- rpart(qualidade ~. - quality,data = dados, control = rpart.control(cp = 0,maxdepth = 4))

predito <- predict(tree,type = "class")

confusionMatrix(predito,dados$qualidade)
table(Predito = predito,Referência = dados$qualidade)
prp(tree,type = 4,box.col=c("#C745C9","#6D85DE", "palegreen3")[tree$frame$yval],tweak = 1.5,fallen.leaves = T,main = "Árvore de Decisão \n Qualidade do Vinho")


```

```{r}
#USADO PCA
wine <- dados[,1:11]
# wine.pca <- prcomp(wine, scale. = TRUE)
# ggbiplot(wine.pca, obs.scale = 1, var.scale = 1,
#          groups = dados[,13], ellipse = TRUE, circle = TRUE) +
#   scale_color_discrete(name = '') +
#   theme(legend.direction = 'horizontal', legend.position = 'top') + theme_bw()


#A PARTIR DAQUI, DEVIDO A SEPARACAO DOS GRUPOS, RESOLVI ANALISAR SEPARADAMENTE
```

#FLORESTA ALEATORIA VINHO BRANCO E VERMELHO
```{r echo=FALSE, warning=FALSE}
#FLORESTA ALEATORIA VINHO BRANCO E VERMELHO
dados$rating[5 >= dados$quality ] = "Ruim"
dados$rating[5< dados$quality & dados$quality < 7] = "Medio"
dados$rating[7<= dados$quality] = "Bom"
dados$rating = as.factor(dados$rating)

dados$rating = relevel(dados$rating, "Ruim")


model_RF = randomForest(rating ~ . -vinho -quality, data=dados)
print(model_RF) 

print(importance(model_RF,type = 2)) 

pred_RF = predict(model_RF)
```

```{r echo=FALSE}
table(dados$rating, pred_RF)
#(1873+2302+840)/(1873+497+14+385+2302+149+26+411+840) = 0.77 precisao
#Da floresta aleatório mostrado acima, podemos concluir que o alcool  eh um fator importante que na qualidade do vinho (ruim, bom, medio). Além disso, o modelo tem apenas 23% de erro que significa que podemos prever com precisão de 77%.
```

```{r echo=FALSE, warning=FALSE}
#FLORESTA ALEATORIA - VINHO VERMELHO
red$rating[5 >= red$quality ] = "Ruim"
red$rating[5< red$quality & red$quality < 7] = "Medio"
red$rating[7<= red$quality] = "Bom"
red$rating = as.factor(red$rating)

red$rating = relevel(red$rating, "Ruim")


V_model_RF = randomForest(rating ~ . -vinho -quality, data=red)
print(model_RF) 

print(importance(V_model_RF,type = 2)) 

V_pred_RF = predict(V_model_RF)
```

```{r echo=FALSE, warning=FALSE}
#FLORESTA ALEATORIA - VINHO BRANCO
white$rating[5 >= white$quality ] = "Ruim"
white$rating[5< white$quality & white$quality < 7] = "Medio"
white$rating[7<= white$quality] = "Bom"
white$rating = as.factor(white$rating)

white$rating = relevel(white$rating, "Ruim")


B_model_RF = randomForest(rating ~ . -vinho -quality, data=white)
print(B_model_RF) 

print(importance(B_model_RF,type = 2)) 

B_pred_RF = predict(B_model_RF)
```



```{r}
#ALCOOL VS DENSIDADE
dados$quality <- as.factor(dados$quality)

dados %>% ggplot(aes(x = density, y = alcohol, color = quality)) +
    facet_wrap(~vinho) + 
    geom_point(size = 3, alpha = 1/4) +
    scale_color_identity(guide = 'legend') +
    ylim(min(dados$alcohol), quantile(dados$alcohol, 0.95)) +
    xlim(min(dados$density), quantile(dados$density, 0.95)) +
    theme_bw() + 
    labs(y = "Alcool",x = "Densidade",color = "Qualidade") 
```


```{r}
#ALCOOL VS ACIDEZ
dados$quality <- as.factor(dados$quality)

dados %>% ggplot(aes(x = volatile.acidity, y = alcohol, color = quality)) +
    facet_wrap(~vinho) + 
    geom_point(size = 3, alpha = 1/4) +
    scale_color_identity(guide = 'legend') +
    ylim(min(dados$alcohol), quantile(dados$alcohol, 0.95)) +
    xlim(min(dados$volatile.acidity), quantile(dados$volatile.acidity, 0.95)) + 
  theme_bw() +
     labs(y = "Alcool",x = "acidez volátil",color = "Qualidade") 
```

```{r}
#volatile.acidity VS density
dados$quality <- as.factor(dados$quality)

dados %>% ggplot(aes(x = volatile.acidity, y = density, color = quality)) +
    facet_wrap(~vinho) + 
    geom_point(size = 3, alpha = 1/4) +
    scale_color_identity(guide = 'legend') +
    ylim(min(dados$density), quantile(dados$density, 0.95)) +
    xlim(min(dados$volatile.acidity), quantile(dados$volatile.acidity, 0.95))  + theme_bw() +
   labs(y = "Densidade",x = "acidez volátil",color = "Qualidade")
```

```{r}
#SULFATO VS ALCOOL
dados$quality <- as.factor(dados$quality)

dados %>% ggplot(aes(x = sulphates, y = alcohol, color = quality)) +
    facet_wrap(~vinho) + 
    geom_point(size = 3, alpha = 1/4) +
    scale_color_identity(guide = 'legend') +
    ylim(min(dados$alcohol), quantile(dados$alcohol, 0.95)) +
    xlim(min(dados$sulphates), quantile(dados$sulphates, 0.95)) +theme_bw() +
  labs(y = "Sulfato",x = "Alcool",color = "Qualidade")
  
```
